server:
  port: 11451

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/teachingassistant?useUnicode=true&characterEncoding=utf8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
    mapper-locations: classpath:mapping/*Mapper.xml
    type-aliases-package: com.ocean.pojo
    config-location: classpath:configuring/mybatis-config.xml
    

